[versions]
agp = "8.8.0"

kotlin = "2.2.10" # Actualice el lenguaje para poder usar KSP

coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"

# Version de KSP
kspVersion = "2.2.10-2.0.2"

# Versiones de Dagger Hilt
hiltAndroid = "2.56"
hiltViewmodel = "1.3.0"

# Retrofit, derivados y asociados
retrofitVersion = "2.9.0"
okhttpVersion = "4.9.0"
loginInterceptorVersion = "4.9.0"

# Version de la dependencia para tener un Navigation Compose
navigationComposeAndroid = "2.9.5"

# Version para serializar JSON
kotlinxSerialization = "1.6.3"
kotlinParcelize = "1.8.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Librerias de Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid"}
hilt-android-compilador = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid"}
hilt-viewmodel = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "hiltViewmodel"}

# Librerias para hacer peticiones API (Retrofit)
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion"}
gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion"}
login-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loginInterceptorVersion"}

# Libreria para utilizar el serialization o parcelizar de Kotlin class a JSON
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization"}

# Libreria para descagar los archivos necesarios para Navigation Compose
androidx-navigation-compose-android = { group = "androidx.navigation", name = "navigation-compose-android", version.ref = "navigationComposeAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Plugin KSP para tener nuevas herramientas de notacion
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion"}

# Plugin para serializar
jetbrainsKotlinSerialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-parcelize = {id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinParcelize"}